import { analyzeText } from './engine.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const input=document.getElementById('thai-input'),out=document.getElementById('results'),status=document.getElementById('status');
function card(token){
  if(token.kind!=="thai") return '<article class="result-card"><div class="result-top"><div><div class="thai">'+esc(token.input)+'</div><div class="subline">'+esc(token.kind)+'</div></div></div></article>';
  const unresolved=token.segmentationStatus==="unresolved";
  const body=token.syllables.map(a=>{
    const ok=a.status==="analyzed";
    return '<div class="syllable-result"><div class="thai" lang="th">'+esc(a.input)+'</div><div class="subline">'+esc(a.status)+'</div>'+(ok?'<div class="data-grid">'+[['ФОНОЛОГІЧНА IPA',a.phonemicIpa],['ПОВЕРХНЕВА IPA',a.phoneticIpa],['ТОН',a.tone&&a.toneIpa?a.tone+' · '+a.toneIpa:'—'],['УКРАЇНСЬКИЙ ПРАКТИЧНИЙ КАНДИДАТ',a.ukrainian||'—']].map(([k,v])=>'<div class="data"><span class="label">'+esc(k)+'</span><div class="value">'+esc(v)+'</div></div>').join('')+'</div>':'')+(a.warnings||[]).map(w=>'<div class="warning">'+esc(w)+'</div>').join('')+'</div>';
  }).join('');
  return '<article class="result-card"><div class="result-top"><div><div class="thai" lang="th">'+esc(token.input)+'</div><div class="subline">сегментація: '+esc(token.segmentationStatus)+'</div></div><span class="badge '+(unresolved?'warn':'ok')+'">'+esc(token.segmentationStatus)+'</span></div>'+body+(token.warnings||[]).map(w=>'<div class="warning">'+esc(w)+'</div>').join('')+'</article>';
}
function run(){const text=input.value.trim();if(!text){status.className='status error';status.textContent='Введіть тайський текст.';out.hidden=true;return}const tokens=analyzeText(text);const thai=tokens.filter(x=>x.kind==="thai");status.className='status';status.textContent='Проаналізовано '+tokens.length+' токен(ів), тайських: '+thai.length+'. Це аналіз написання, а не переклад.';out.innerHTML=tokens.map(card).join('');out.hidden=false;out.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);const old=b.textContent;b.textContent='Скопійовано';setTimeout(()=>b.textContent=old,900)}catch{}})}
document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.example;input.focus()}));document.getElementById('clear').addEventListener('click',()=>{input.value='';out.hidden=true;status.textContent=''});document.getElementById('analyze').addEventListener('click',run);